<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Roslyn -->
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.12.0" />

    <!-- MSBuild -->
    <PackageVersion Include="Microsoft.Build.Framework" Version="17.12.6" />
    <PackageVersion Include="Microsoft.Build.Utilities.Core" Version="17.12.6" />

    <!-- Validation -->
    <PackageVersion Include="FluentValidation" Version="11.11.0" />

    <!-- Testing -->
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="Verify.Xunit" Version="28.3.1" />
    <PackageVersion Include="Microsoft.Playwright" Version="1.57.0" />
  </ItemGroup>
</Project>
