import { defineConfig } from 'vite'
import { TanStackRouterVite } from '@tanstack/router-plugin/vite'
import react from '@vitejs/plugin-react'
import tailwind from '@tailwindcss/vite'
import path from 'path'
import { routes } from './Generated/shalimar-routes.g'

export default defineConfig({
    plugins: [
        tailwind(),
        // TanStack Router plugin with virtual file routes (generated by Shalimar)
        TanStackRouterVite({
            target: 'react',
            virtualRouteConfig: routes,
            routesDirectory: '.',
            generatedRouteTree: './Generated/routeTree.gen.ts',
            quoteStyle: 'single',
        }),
        react(),
    ],
    resolve: {
        alias: {
            '@generated': path.resolve(__dirname, './Generated'),
            '@features': path.resolve(__dirname, './Features'),
            '@shalimar/runtime': path.resolve(__dirname, './Shared/runtime'),
        }
    },
    build: {
        manifest: true,
        outDir: 'wwwroot/dist',
        emptyOutDir: true,
        rollupOptions: {
            input: 'Features/App/main.tsx',
            output: {
                entryFileNames: 'assets/[name]-[hash].js',
                chunkFileNames: 'assets/[name]-[hash].js',
                assetFileNames: 'assets/[name]-[hash][extname]',
            },
        },
    },
    server: { port: 5173, strictPort: true, cors: true },
})
