import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { TanStackRouterVite } from '@tanstack/router-plugin/vite'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

// Shalimar: TanStack virtual file routes are the only allowed routing mode.
// The virtual config is generated by the Shalimar source generator into Generated/.
export default defineConfig({
    resolve: {
        alias: {
            '@generated': path.join(fileURLToPath(new URL('.', import.meta.url)), 'Generated'),
        },
    },
    plugins: [
        react(),
        TanStackRouterVite({
            // Route modules are virtual and may live under both Features/ and Generated/.
            // Root route lives under Features/App/root.tsx.
            routesDirectory: '.',
            virtualRouteConfig: 'Generated/shalimar-routes.g.ts',
            generatedRouteTree: 'Generated/routeTree.gen.ts',
        }),
    ],
})

