#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Runs Shalimar tests.
.PARAMETER Unit
    Run only unit tests (non-Integration)
.PARAMETER Integration
    Run only Playwright integration tests
.PARAMETER Port
    Port for IntegrationApp. Default: 5099
#>
param(
    [switch]$Unit,
    [switch]$Integration,
    [int]$Port = 5099,
    [switch]$NoBuild
)
$ErrorActionPreference = "Stop"

$RepoRoot = Join-Path $PSScriptRoot ".."
$AppDir = Join-Path $RepoRoot "src/Shalimar.IntegrationApp"

function Test-PortAvailable([int]$port) {
    try {
        $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $port)
        $listener.Start()
        $listener.Stop()
        return $true
    } catch {
        try { if ($listener) { $listener.Stop() } } catch { }
        return $false
    }
}

function Get-FreeTcpPort() {
    $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, 0)
    $listener.Start()
    $port = $listener.LocalEndpoint.Port
    $listener.Stop()
    return $port
}

# If neither specified, run both
$runUnit = $Unit -or (-not $Unit -and -not $Integration)
$runIntegration = $Integration -or (-not $Unit -and -not $Integration)

if ($runUnit) {
    Write-Host "Running unit tests..." -ForegroundColor Cyan
    $unitProjects = @(
        "$RepoRoot/tests/Shalimar.Runtime.Tests/Shalimar.Runtime.Tests.csproj",
        "$RepoRoot/tests/Shalimar.SourceGenerator.Tests/Shalimar.SourceGenerator.Tests.csproj",
        "$RepoRoot/tests/Shalimar.RoslynAnalyzer.Tests/Shalimar.RoslynAnalyzer.Tests.csproj",
        "$RepoRoot/tests/Shalimar.MSBuildTasks.Tests/Shalimar.MSBuildTasks.Tests.csproj",
        "$RepoRoot/tests/Shalimar.Vite.Tests/Shalimar.Vite.Tests.csproj"
    )

    foreach ($project in $unitProjects) {
        $args = @($project)
        if ($NoBuild) { $args += "--no-build" }
        dotnet test @args
        if ($LASTEXITCODE -ne 0) { throw "Unit tests failed: $project" }
    }
}

if ($runIntegration) {
    Write-Host "`nRunning Playwright integration tests..." -ForegroundColor Cyan

    if (-not (Test-Path $AppDir)) {
        throw "IntegrationApp not found. Run ./scripts/integration.ps1 first"
    }

    # Install Playwright browsers if needed (generated by Microsoft.Playwright package)
    Write-Host "  Ensuring Playwright browsers are installed..."
    $playwrightDir = Join-Path $RepoRoot "tests/Shalimar.IntegrationPlaywrightTests"
    dotnet build $playwrightDir
    if ($LASTEXITCODE -ne 0) { throw "Playwright test project build failed" }
    $pwScript = Get-ChildItem (Join-Path $playwrightDir "bin") -Recurse -Filter "playwright.ps1" -ErrorAction SilentlyContinue | Select-Object -First 1
    if (-not $pwScript) { throw "playwright.ps1 not found under $playwrightDir/bin - build may have failed" }
    & $pwScript.FullName install chromium
    if ($LASTEXITCODE -ne 0) { throw "Playwright browser install failed" }

    # Start IntegrationApp
    $effectivePort = $Port
    if ($effectivePort -le 0) {
        $effectivePort = Get-FreeTcpPort
    } elseif (-not (Test-PortAvailable $effectivePort)) {
        $effectivePort = Get-FreeTcpPort
        Write-Host "  Port $Port is in use; using $effectivePort instead." -ForegroundColor Yellow
    }

    Write-Host "  Starting IntegrationApp on port $effectivePort..."
    Push-Location $AppDir
    $env:ASPNETCORE_URLS = "http://localhost:$effectivePort"
    $env:ASPNETCORE_ENVIRONMENT = "Production"

    $logFile = Join-Path $AppDir "app.log"
    $tfm = "net10.0"
    $config = "Debug"
    $exe = Join-Path $AppDir "bin/$config/$tfm/Shalimar.IntegrationApp"
    if ($IsWindows) { $exe = "$exe.exe" }
    if (-not (Test-Path $exe)) {
        Pop-Location
        throw "IntegrationApp build output not found at '$exe'. Run ./scripts/integration.ps1 first."
    }

    # Cross-platform: use Start-Process without -WindowStyle on non-Windows
    if ($IsWindows) {
        $process = Start-Process $exe -PassThru -RedirectStandardOutput $logFile -RedirectStandardError "$logFile.err" -WindowStyle Hidden
    } else {
        $process = Start-Process $exe -PassThru -RedirectStandardOutput $logFile -RedirectStandardError "$logFile.err"
    }

    # Wait for app to be ready
    $ready = $false
    Write-Host "  Waiting for app to start..."
    for ($i = 0; $i -lt 30; $i++) {
        Start-Sleep 1
        try {
            $response = Invoke-WebRequest "http://localhost:$effectivePort" -UseBasicParsing -TimeoutSec 2 -ErrorAction SilentlyContinue
            if ($response.StatusCode -eq 200) {
                $ready = $true
                break
            }
        } catch { }
    }

    if (-not $ready) {
        if (-not $process.HasExited) { $process.Kill() }
        Pop-Location
        Write-Host "App log:" -ForegroundColor Yellow
        if (Test-Path $logFile) { Get-Content $logFile -Tail 20 }
        throw "IntegrationApp failed to start within 30 seconds"
    }

    Write-Host "  App is ready!" -ForegroundColor Green
    Pop-Location

    try {
        $env:INTEGRATION_APP_URL = "http://localhost:$effectivePort"
        $args = @("$RepoRoot/tests/Shalimar.IntegrationPlaywrightTests", "--filter", "Category=Integration")
        if ($NoBuild) { $args += "--no-build" }
        dotnet test @args
        $testResult = $LASTEXITCODE
    } finally {
        Write-Host "  Stopping IntegrationApp..."
        if (-not $process.HasExited) { $process.Kill() }
    }

    if ($testResult -ne 0) { throw "Integration tests failed" }
}

Write-Host "`n✓ All tests passed" -ForegroundColor Green
